config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'enrG+', to: 'static_pages#enrG+', as: 'enrg-plus'
  get 'menu' => 'static_pages#menu'
  get 'iv-therapy' => 'static_pages#iv-therapy'
  get 'page' => 'static_pages#page'
  get 'staff' => 'static_pages#staff'


  get '/fb', to: 'links#fb'
  get '/insta', to: 'links#insta'
  get '/hsdh', to: 'links#hsdh'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	def fb
	    redirect_to('https://www.facebook.com/enrgiv/')
	end

	def insta
		redirect_to('https://www.instagram.com/suemeyers2457/')
	end

	def hsdh
		redirect_to('https://hsdesignhouse.com')
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	layout 'application'

	def home
	end

	def contact
	end
end



#{@contact.name}

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="top">
		<div class="col-md-6 soc">
			<ul class="social">
				<li class="title">Follow Us:</li>
				<li><%= link_to '/fb' do %> <i class="fa fa-facebook"></i> <% end %></li>
				<li><%= link_to '/insta' do %> <i class="fa fa-instagram"></i> <% end %></li>
			</ul>
		</div>

		<div class="col-md-6 con">
			<ul class="contact">
				<li><%= number_to_phone(2512400842, delimiter: '.') %></li>
				<li>info@enrgiv.com</li>
			</ul>
		</div>
	</div>

	<div class="blue-block">
		<div class="container">
			<ul class="ft-menu">
		    <li class="menu-item"><%= link_to "Home", root_path %></li>
    		<li class="menu-item"><%= link_to "Our IV Menu", menu_path %></li>
		    <li class="menu-item"><%= link_to "Functional Medicine", enrg_plus_path %></li>
		    <li class="menu-item"><%= link_to "Contact", contact_path %></li>
			</ul>

			<!-- <div class="cta-sec"> <h4>Call Today for an Appointment</h4> </div> -->
			<div class = "cta-sec"><%= render 'chimp' %></div>
		</div>
	</div>

	<div class="bottom">
		<div class="container">
			<p class="loc">3099 Loop Rd <span><i class="fa fa-circle"></i></span> Orange Beach, Al 36561</p>
			<p class="copy">Copyright <%= Time.now.year %>. All rights reserved. <span>Design by <%= link_to "High Seas Design House.", hsdh_path, :target => "_blank" %></span> </p>
		</div>
	</div>
  <a href="#" class="scroll-up">Scroll</a>
</footer>


<%= render 'static_pages/modals' %>

<div class="offcanvas-menu">
    <a class="close-offcanvas" href="#"><i class="fa fa-close"></i></a>
    <div class="offcanvas-inner">
        <div class="module">
            <!-- <h3 class="module-title">Main Menu</h3> -->

            <div class="module-content">
              <ul class="nav menu">
						    <%= render 'layouts/nav' %>
              </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_ga-code.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98605626-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<!-- <header>
	<div id="nav" class="stick">

		<div class="book-bar reg">
			<div class="contact-info">
				<h4 class="phone"><span>Call for Appointment:</span> <%= number_to_phone(2512400842, delimiter: '.') %></h4>
				<h4 class="wiw">Walk-Ins Welcome</h4>
				<ul class="social">
					<li><%= link_to '/fb' do %> <i class="fa fa-facebook"></i> <% end %></li>
					<li><%= link_to '/insta' do %> <i class="fa fa-instagram"></i> <% end %></li>
				</ul>
			</div>
		</div>

		<div class="container sm-pad">
			<% unless current_page?(enrg_plus_path) %>
		    <div class="logo-block"><%= link_to(image_tag( 'enrg-web.png', alt: 'enrG IV Logo', class: 'img-responsive logo'), root_path ) %></div>

		    <% else %>
			    <div class="logo-block"><%= link_to(image_tag( 'nrg-plus.png', alt: 'enrG Plus Logo', class: 'img-responsive logo'), root_path ) %></div>
	    <% end %>
			<nav>
				<ul class="megamenu-parent menu-zoom hidden-xs">
			    <%= render 'layouts/nav' %>
				</ul>
			</nav>

				<div>
			    <a href="#" id="offcanvas-toggler">
			        <span></span>
			        <span></span>
			        <span></span>
			    </a>
			  </div>
		</div>
	</div>
</header>
 -->

<header>
	<div id="nav" class="stick">

		<div class="book-bar new">
			<div class="contact-info">
				<div class="block one"><h4 class="phone"><span>Call Us:</span> <%= number_to_phone(2512400842, delimiter: '.') %></h4></div>
				<div class="block two">
					<ul class="social">
						<li><%= link_to '/fb' do %> <i class="fa fa-facebook"></i> <% end %></li>
						<li><%= link_to '/insta' do %> <i class="fa fa-instagram"></i> <% end %></li>
					</ul>
				</div>
				<div class="block three"><h4 class="wiw">We Have a Professional Medical Staff. &nbsp;<br class="xs"> <span>Walk-Ins Welcome!</span></h4></div>
			</div>
		</div>

		<div class="container sm-pad">
			<% unless current_page?(enrg_plus_path) %>
		    <div class="logo-block"><%= link_to(image_tag( 'enrg-web.png', alt: 'enrG IV Logo', class: 'img-responsive logo'), root_path ) %></div>

		    <% else %>
			    <div class="logo-block"><%= link_to(image_tag( 'nrg-plus.png', alt: 'enrG Plus Logo', class: 'img-responsive logo'), root_path ) %></div>
	    <% end %>
			<nav>
				<ul class="megamenu-parent menu-zoom hidden-xs">
			    <%= render 'layouts/nav' %>
				</ul>
			</nav>

				<div>
			    <a href="#" id="offcanvas-toggler">
			        <span></span>
			        <span></span>
			        <span></span>
			    </a>
			  </div>
		</div>
	</div>
</header>

app/views/layouts/_nav.html.erb
<li class="menu-item"><%= link_to "Home", root_path %></li>
<li class="menu-item"><%= link_to "IV Menu", menu_path %></li>
<li class="menu-item"><%= link_to "Functional Medicine", enrg_plus_path %></li>
<li class="menu-item"><%= link_to "Our Staff", staff_path %></li>
<!-- <li class="menu-item noft"><a data-uk-modal="{center:true}" class="modal3" href="#appt">Book Now</a></li> -->
<li class="menu-item"><%= link_to "Contact", contact_path %></li>

app/views/layouts/_rails_default.html.erb
<!-- Required meta tags always come first -->
   <!--  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge"> -->
    <meta name="description" content= "<%= @page_description %>">
    <title><%= @page_title  %> | ENRG IV Bar</title>

		<%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
 <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= favicon_link_tag 'ivcon.png' %>

    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

    <body class=" <%= controller_name %> <%= action_name %>">
      <%= render 'layouts/ga-code' %>
      <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/_book-now.html.erb
<div class="uk-modal" id="appt">
  <div class="uk-modal-dialog uk-modal-dialog-large">
    <a class="uk-modal-close uk-close"><i class="fa fa-close"></i></a>
    <div class="content">
			<iframe src="https://drchrono.com/scheduling/offices/139140" width="100%" height="1750px" frameborder="0"></iframe>
    </div>
  </div>
</div>

app/views/static_pages/_chimp.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<div id="mc_embed_signup">
	<form action="//enrgiv.us15.list-manage.com/subscribe/post?u=9096047fd55410a553666b862&amp;id=04edaabf87" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
			<h3 class="head">Subscribe for updates, deals, and news!</h3>
    <div id="mc_embed_signup_scroll">
			<label for="mce-EMAIL"></label>
			<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" required>
	    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_9096047fd55410a553666b862_04edaabf87" tabindex="-1" value=""></div>
	    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
	</form>
</div>

app/views/static_pages/_cocktails.html.erb
<ul class="ch-grid">
					<li>
						<div class="ch-item hangover">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Over Indulgence</h4>
										<h3>Never Again</h3>
										<hr>
										<p><span>	<i class="fa fa-tint"></i> b-complex, + more!</span></p>
									</div>
									<div class="ch-info-back">
										<p>Don't let a night of fun keep you in bed for days after. Visit us for some IV therapy to help you rehydrate, and relieve your hangover symptoms!</p>
										<!-- <p>Don't let a night of fun keep you in bed for days after. Visit us for some IV hangover therapy. enrG IV can help you rehydrate, and eliminate the hangover symptoms that end your day before it starts.</p> -->
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item beauty">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Beauty &amp; Anti-aging</h4>
										<h3>Princess Again</h3>
										<hr>
										<p><span><i class="fa fa-tint"></i> b-complex, magnesium, vitamin c</span></p>
									</div>
									<div class="ch-info-back less">
										<!-- <p>Hydration is the key to youthful skin. Our anti-aging drip can improve dry skin, blemishes, and signs of aging, and help restore that healthy glow you want. Maybe our laugh lines and frown lines help tell our story, but we'd rather remain mysterious!</p> -->
										<p>Hydration is the key to youthful skin. Our anti-aging drip can improve dry skin, blemishes, and signs of aging. Maybe our laugh lines help tell our story, but we'd rather remain mysterious!</p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item wellness">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Health &amp; Wellness</h4>
										<h3>I Feeeeeel Good</h3>
										<hr>
										<p><span>	<i class="fa fa-tint"></i> vitamin c, b-complex, magnesium, amino acids</span></p>
									</div>
									<div class="ch-info-back less">
										<p>
										<!-- Maintaining a healthy lifestyle isn't easy, so we want all of our attempts to work. Even the best multi-vitamins and supplements only average about 20% absorption when taken orally. IV therapy is a great way to keep up your health, stay hydrated, and get maximum vitamin absorption.</p> -->
										<!-- Maintaining a healthy lifestyle is hard, so we want all of our attempts to work.  -->
										Even the best multi-vitamins/supplements, when taken orally, only average 20% absorption. IV therapy is a great way to boost your health and stay hydrated, with maximum absorption.</p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item flu">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Cold &amp; Flu</h4>
										<h3>Get Over It</h3>
										<hr>
										<p><span>	<i class="fa fa-tint"></i> vitamin c, zinc, magnesium</span></p>
									</div>
									<div class="ch-info-back">
										<!-- <p>No one wants to feel cold and stuffy at the beach! enrG IV has a drip that will help you drop that sickness. Come see us, and we'll get your toes back in the sand in no time! </p> -->
										<p>No one wants to feel cold and stuffy at the beach! Come see us, and we'll get your toes back in the sand in no time! </p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item fatigue">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Fatigue &amp; Jet Lag</h4>
										<h3>Myers Cocktail</h3>
										<hr>
										<p><span>	<i class="fa fa-tint"></i> b-complex, vitamin c, magnesium, + more</span></p>
									</div>
									<div class="ch-info-back">
										<!-- <p>Traveling adds stress to the body, often altering routines in an unhealthy way. You can't enjoy our beautiful beaches if your body feels dehydrated and fatigued. enrG IV has the drip that will refill your tank! </p> -->
										<p>You can't enjoy our beautiful beaches if your body feels dehydrated and fatigued. enrG IV has the drip that will refill your tank! </p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item sports">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Athletic Performance</h4>
										<h3>Elephant Stomper/<br>Tiger Killer</h3>
										<hr>
										<p><span>	<i class="fa fa-tint"></i> b-complex, magnesium, amino acids</span></p>
									</div>
									<div class="ch-info-back less">
										<p>enrG IV can help you enhance your performance, and speed up your recovery. Adequate hydration and nutrients make it possible to push yourself and keep improving.</p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item immune">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Immune Support</h4>
										<h3>Vim &amp; Vigor</h3>
										<hr>
										<p><span><i class="fa fa-tint"></i>
											Vitamin C, b-complex, and other powerful minerals and antioxidants
										</span></p>
									</div>
									<div class="ch-info-back">
										<p>If you suffer from chronic illness, and need extra support, or if you just want a quick way to boost your energy and/or immune system, you found it!</p>
										<!-- <p>We use minerals crucial to hundreds of metabolic reations throughout the body (zinc, selenium, and magnesium)</p> -->
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item women">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Libido Support for Women</h4>
										<h3>I’ll Have What She’s Having</h3>
										<hr>
										<p><span><i class="fa fa-tint"></i>B-complex, Amino Acids + ask about our secret ingredient</span></p>
									</div>
									<div class="ch-info-back">
										<p>You get it.</p>
									</div>
								</div>
							</div>
						</div>
					</li>

					<li>
						<div class="ch-item men">
							<div class="ch-info-wrap">
								<div class="ch-info">
									<div class="ch-info-front ch-img">
										<h4>Libido Support for Men</h4>
										<h3>The All-Nighter</h3>
										<hr>
										<p><span><i class="fa fa-tint"></i>B-complex, Amino Acids + ask about our secret ingredient</span></p>
									</div>
									<div class="ch-info-back">
										<p>You get it.</p>
									</div>
								</div>
							</div>
						</div>
					</li>
				</ul>

app/views/static_pages/_modals.html.erb
<div class="modal-coll">

		<div class="uk-modal" id="members">
		  <div class="uk-modal-dialog">
		    <a class="uk-modal-close uk-close"><i class="fa fa-close"></i></a>
				<!-- <div id="#members"> -->
				<div class="content">
					<div class="sec1">
						<%= image_tag('menu-circlesblue.png', class: 'img-responsive icon', alt: 'enrG Plus Logo') %>
						<h2>Join the Club</h2>
						<h3>enrG IV Members save big!</h3>
						<h4>We offer <b>3 Month</b>, <b>6 Month</b>, and <b>12 Month</b> Membership Packages. Choose a plan today, and boost your savings as you boost your health! </h4>
						<div class="title-line"></div>
					</div>

					<div class="monthly one"><h4>3 Month:<br> <span>$109/mo.</span></h4></div>
					<div class="monthly two"><h4>6 Month:<br> <span>$99/mo.</span></h4></div>
					<div class="monthly last"><h4>12 Month:<br> <span>$69/mo.</span></h4></div>

					<div class="mem-box">
						<h3>What do members get? </h3>
						<div class="title-line"></div>
						<p class="pleft"><i class="fa fa-tint"></i> The first treatment each month,<br><span> free of charge</span></p>
						<div class="title-line"></div>
						<p class="pleft"><i class="fa fa-tint"></i> 15% off all supplements</p>
						<div class="title-line"></div>
						<p><span class="print">*IV Drips regularly cost $149 </span></p>
					</div>
				</div>
			</div>
		</div>

		<div class="uk-modal" id="clinic">
		  <div class="uk-modal-dialog">
		    <a class="uk-modal-close fa fa-close"></a>
		    <div class="content">
							<h2>Clinic Visits</h2>
							<p>All visits include extensive history and physical assessment, initial dietary and supplement recommendations, and laboratory recommendations.</p>

							<hr>
							<h4>Initial Visit Cost:</h4>
							<p><b>Doctor's Office</b>... $299</p>
							<p><b>Nurse Practioner</b>... $245</p>
							<p><b>RN</b>... $199</p>
							<hr>
						<p class="fine">*Some laboratory expenses may be covered by insurance.<br> Others may be out of pocket expenses.</p>
		    </div>
		  </div>
		</div>

		<div class="uk-modal" id="deal">
		  <div class="uk-modal-dialog">
		    <a class="uk-modal-close uk-close"><i class="fa fa-close"></i></a>
		    <div class="content specials">
					<h3 class="blue">Get 4 IV’s for $429 </h3>
					<h4> No Membership Required!</h4>
					<p><span>*IV Drips regularly cost $149 each. </span></p>
					<hr><div class="clearfix"></div>
					<%= link_to "View Our IV Menu", menu_path, class: 'modal-link' %>
				</div>
			</div>
		</div>

		<div class="uk-modal" id="package">
		  <div class="uk-modal-dialog">
		    <a class="uk-modal-close uk-close"><i class="fa fa-close"></i></a>
		    <div class="content specials">
		    			<h3 class="blue">Weight Loss Package</h3>
							<h4>$350 Nutritional Program</h4>
		    			<div class="col-md-6"><hr></div>
		    			<div class="clearfix"></div>
							<p>Fitness plan, detoxification plan with supplements</p>
							<p>4 weekly evaluations, with body composition analysis. </p>
							<p>Lipotropic enrgy boosting injections at each visit.</p>
				</div>
			</div>
		</div>



		<div class="uk-modal" id="appt">
		  <div class="uk-modal-dialog uk-modal-dialog-large">
		    <a class="uk-modal-close uk-close"><i class="fa fa-close"></i></a>
		    <div class="content">
					<iframe src="https://drchrono.com/scheduling/offices/139140" width="100%" height="1750px" frameborder="0"></iframe>
		    </div>
		  </div>
		</div>



</div>

app/views/static_pages/contact.html.erb
<% @page_title = "Contact Us" %>
<% @page_description = "enrG IV is a Vitamin IV Bar & Functional Medicine Clinic located in Orange Beach, Al. Contact us for more information on our services, or to schedule an appointment." %>

<div class="pages-wrap">
		<div class="combo-header">
			<div class="container">
				<div class="text-box">
					<h1>Contact Us</h1>
				</div>
			</div>
		</div>

		<div class="contact-sec">
			<div class="container">
					<!-- <div class="col-md-8"> -->
						<div class="col-md-4 info">
							<h4><%= number_to_phone(2512400842, delimiter: '.') %></h4>

							<h4>info@enrgiv.com</h4>

							<h4>3099 Loop Rd<br> Orange Beach, Al 36561</h4>

							<ul class="social">
								<li><%= link_to '/fb' do %> <i class="fa fa-facebook"></i> <% end %></li>
								<li><%= link_to '/insta' do %> <i class="fa fa-instagram"></i> <% end %></li>
							</ul>
						</div>

						<div class="col-md-4 hours">
							<h4><span>Hours of Operation:</span><div class="title-line"></div></h4>

							<h4> Monday - Friday: 10am-6pm<br> Saturday - Sunday: 10am - 3pm<br><b>Closed Tuesdays</b></h4>
							<p> <b>After Hours Appointments Available</b></p>
						</div>
					<!-- </div> -->

				<div class="col-md-4 links">
					<%= link_to '/menu', class: 'link-box' do %>
						<div class="inside">
							<h4>View Our<br> <span>Signature Cocktails</span></h4>
						</div>
					<% end %>

					<%= link_to enrg_plus_path, class: 'link-box' do %>
						<div class="inside">
							<h4>Learn More About<br> <span>Functional Medicine</span></h4>
						</div>
					<% end %>
				</div>

			</div>
		</div>
</div>

app/views/static_pages/staff.html.erb
<% @page_title = "Our Staff" %>
<% @page_description = "enrG+ is the functional medicine side of our clinic. Our staff includes licensed, medical professionals, and leaders in the IV Therapy industry. " %>


<div class="pages-wrap">

	<div class="pages-header">
		<div class="container">
			<h1>Our Staff</h1>
		</div>
	</div>


	<div class="full-section">
		<div class="container">
			<div class="col-md-8 no-padding col-md-offset-2 text-center">
				<p><b>enrG IV has a full staff of licensed, medical professionals.</b> Our team includes expert​s​ who have been specially trained in IV Vitamin Therapies and Functional Medicine. Pictures coming soon!</p>
				<div class="title-line"></div>
			</div>
			<div class="clearfix"></div>

			<div class="row doctor">
					<!-- <div class="col-md-4 no-padding">
						<%=image_tag('staff1.jpg', class: 'img-responsive', alt: 'Dr. Jun Yoo, Chief Medical Director') %>
					</div> -->

					<div class="col-md-10 bio">
						<h3>Meet Our Doctor</h3>
						<p>Dr. Jun Yoo, D.O., is the Chief Medical Director of enrG+, LLC, and enrG IV. Dr. Yoo grew up in Central California, and received his Biology Degree from California State University, with a minor in Chemistry. He continued to earn his Doctor of Osteopathy from Midwestern University, Arizona College of Osteopathic Medicine.</p>

						<p>As he moved East, Dr. Yoo became Chief Resident at Sacred Heart Internal Medicine, in Pensacola, Florida. Along with his position as Chief Medical Director of enrG+, LLC and enrG IV, Dr. Yoo is also the Doctor of Internal Medicine at West Florida Hospital in Pensacola.</p>
					</div>
			</div>
		</div>
	</div>

	<div class="med-link">
		<div class="container">
			<h3><%= link_to "Click Here to Learn More About Functional Medicine", enrg_plus_path %></h3>
		</div>
	</div>
</div>